export const images={hero:'https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=2000&q=88',education:'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=85',health:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=85',volunteer:'https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&q=85',women:'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=85',youth:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=85',food:'https://images.unsplash.com/photo-1593113598332-cd288d649433?auto=format&fit=crop&w=1200&q=85',temple:'https://images.unsplash.com/photo-1524613032530-449a5d94c285?auto=format&fit=crop&w=1200&q=85'};
export const activities=[
 {slug:'blood-donation-camp',title:'Blood Donation Camp',tag:'Healthcare',image:'https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=1200&q=85',description:'Community-led blood donation drives connecting compassionate donors with regional hospitals.'},
 {slug:'village-education-initiative',title:'Village Education Initiative',tag:'Education',image:images.education,description:'Learning resources, mentorship and scholarships that help young minds thrive.'},
 {slug:'medical-checkup-camp',title:'Medical Checkup Camp',tag:'Wellbeing',image:images.health,description:'Accessible preventive healthcare and specialist consultations for rural families.'},
 {slug:'food-distribution',title:'Food Distribution',tag:'Seva',image:images.food,description:'Dignified food support delivered with care to families facing difficult moments.'},
 {slug:'women-empowerment-workshop',title:'Women Empowerment Workshop',tag:'Community',image:images.women,description:'Skills, confidence and community networks for women building independent futures.'},
 {slug:'youth-leadership-camp',title:'Youth Leadership Camp',tag:'Youth',image:images.youth,description:'Values-led leadership experiences for the next generation of community builders.'}
];
export const programs=[
 {slug:'join-sarak',title:'Join SARAK',image:images.volunteer,description:'Become part of a purposeful network rooted in seva, Jain values and collective progress.',deadline:'Open throughout the year',state:'open'},
 {slug:'join-paryushan',title:'Join Paryushan',image:images.temple,description:'Experience reflection, learning and service during the sacred festival of self-purification.',deadline:'Registration closes in 5 days',state:'open'},
 {slug:'join-salgirah',title:'Join Salgirah',image:'https://images.unsplash.com/photo-1606298855672-3efb63017be8?auto=format&fit=crop&w=1200&q=85',description:'Celebrate our shared journey with a day of gratitude, culture and community.',deadline:'Registration closes on 28 Aug',state:'open'},
 {slug:'volunteer-registration',title:'Volunteer Registration',image:'https://images.unsplash.com/photo-1542810634-71277d95dcbb?auto=format&fit=crop&w=1200&q=85',description:'Offer your time and talent across education, health, events and outreach.',deadline:'Registrations Closed',state:'closed'}
];
export const gallery=[activities[0].image,images.education,images.health,images.volunteer,images.women,images.youth,images.food,images.temple,'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=85'];
